spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Peter Ray - QA Lead"
    email: "peter@eazybank.com"
  onCallSupport:
    - (666) 265-1234
    - (666) 734-1345