spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related Prod APIs "
  contactDetails:
    name: "Bella Aishwarya - Product Owner"
    email: "bella@eazybank.com"
  onCallSupport:
    - (453) 392-1234
    - (236) 203-1345