services:
  configserver:
    image: "ubaclone/configserver:v2"
    container_name: configserver-ms
    ports:
      - "8030:8030"
    healthcheck:
      test: "curl --fail --silent localhost:8030/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "ubaclone/eurekaserver:v2"
    container_name: eurekaserver-ms
    ports:
      - "8040:8040"
    healthcheck:
      test: "curl --fail --silent localhost:8040/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  accounts:
    image: "ubaclone/accounts:v2"
    container_name: account-ms
    ports:
      - "8060:8060"
    healthcheck:
      test: "curl --fail --silent localhost:8060/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  eservice:
    image: "ubaclone/eservices:v2"
    container_name: eservice-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eservice"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  gatewayserver:
    image: "ubaclone/gatewayserver:v2"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      accounts:
        condition: service_healthy
      eservice:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  ubaclone:
    driver: "bridge"

