CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	customer_id INT NOT NULL UNIQUE,
	created_at DATE NOT NULL,
	created_by VARCHAR(50) NOT NULL,
	updated_at DATE DEFAULT NULL,
	updated_by VARCHAR(50) DEFAULT NULL
);