spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related Prod APIs "
  contactDetails:
    name: "Tom Aishwarya - Product Owner"
    email: "tom@eazybank.com"
  onCallSupport:
    - (888) 392-1234
    - (888) 203-1345