spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Opeseen/JAVA_MICROSERVICES.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-paths: "section6/v2-springcloud/appGitConfig"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: ABCD123456908645HFTWAVBRPLMDH

server:
  port: 8071